
name: deploy cloud functions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: yarn build-functions
      - name: Deploy to Firebase
        uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}